### DISCUSSION TITLE
03-cd생성

### DISCUSSION THREAD

**Discussion by kimziou77** [kimyo-study/CICDpractice#5] [진행 기록]
###  스크립트 이름과 깃헙 액션을 실행할 이벤트를 정의해준다

```yml
name: kimyo first main branch deploy

on:
  push:
    branches:
      - "main*"
```
우선 main에 push할때 deploy 하는걸로 설정한다

### 작업들을 jobs 안에 정의한다
```yml
jobs:
  build:
    runs-on: ubuntu-latest
```
환경은 우분투에서 돌아가도록.. 우리팀의 우분투 버전은 18.04였는데 latest인가?

### 작업안에서 진행할 스텝들을 정의해준다

```yml
    steps:
      - name: 1. what is this
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 2. Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: 3. Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 5. OpenAPI Spec Create
        run: |
          export SERVER_NAME=${{ secrets.SERVER_NAME }}
          ./gradlew test copyDocument
      - name: Execute Gradle build
        run: |
#          export KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
#          export KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
#          export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          ./gradlew build jib

      - name: 6. jenkins deploy
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_WEBHOOK_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_USER_TOKEN }}
          job: ${{ secrets.JEKINS_DEV_JOB }}
```
1. What is this
  얜 머하는 애인지 잘 모르겠다 
3. Set up JDK 17
  자바 17버전을 사용하기 위해서 
5. Cache Gradle packages
  얘도 무엇인지 잘 모르겠다
7. Log in to Docker Hub
  이 부분을 내 계정으로 변경해야 할 것 같다
9. OpenAPI Spec Create
  테스트코드를 돌려 swagger를 생성해냈던 부분이다. 
10.  jenkins deploy
  여기서 deploy가 되는 것 같다.

### 다음 환경변수를 깃헙 secerets에 등록한다
DOCKER_USERNAME 
DOCKER_PASSWORD 
SERVER_NAME 
주석 처리한 부분은 이번 프로젝트에선 사용하지 않지만 이전 프로젝트 build시 필요했던 환경변수이다.

### 이제 환경을 세팅해준다
현재 예상되는 작업은 다음과 같다
- 환경변수를 등록하기 위한 도커 작업
- 도커에 띄우기 위한 프로젝트 생성
- 도메인 발급
